name: pipeline for testing

on:
  push:
    branches: [main]

jobs:

  job-name:
    runs-on: ubuntu-latest
    steps:
      - name: check the code
        uses: actions/checkout@v4

      - name: do something
        uses: actions/setup-python@v5
        with:  
          python-version: '3.14'

      - name: do something
        run: pip install fastapi uvicorn

      - name: check uvicorn running
        run: uvicorn --version
          
